python code/train.py \
    --train_path "data/preprocess_data/train.csv" \
    --save_model_path "model/cpu/H" \
    --prev_day 10 \
    --pred_day 3 \
    --epochs 5 \
    --batch_size 128 \
    --verbose 1 \
    --shuffle false \